INSERT INTO `tb_ips`
VALUES
(1, 'ESE I NIVEL', 0),
(2, 'HOSPITAL SAN JOSÉ DEL GUAVIARE', 0),
(3, 'ODONTOMEDIC IPS', 0),
(4, 'NUEVA SALUD INTEGRAL IPS', 0),
(5, 'CENTRO MEDICO GUAVIARE', 0),
(6, 'IPS SESMAS', 0),
(7, 'ANGIAGRAFIAS DE COLOMBIA', 0),
(8, 'MI IPS LLANOS', 0),
(9, 'VISIÓN ORAL DIGITAL', 0),
(10, 'GAMMAS IPS', 0);